name: Coverage Report
on:
  push:
    branches:
      - main

jobs:
  test:
    name: Jest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 14
      - run: npm install
      - run: npm test
      - uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: coverage
  coveralls:
    needs: test
    name: Coveralls
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: coverage-report
      - run: ls -l coverage
      - uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
  codecov:
    needs: test
    name: Codecov
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: coverage-report
      - run: ls -l coverage
      - name: Upload coverage reports to Codecov with GitHub Action
        uses: codecov/codecov-action@v3
