name: Build with Quality Scans
on:
  push:
    branches:
      - main

jobs:
  test:
    uses: ./.github/workflows/npm-install-test.yml
  coveralls:
    needs: test
    uses: ./.github/workflows/coveralls.yml
  codecov:
    needs: test
    uses: ./.github/workflows/codecov.yml
  sonar:
    needs: test
    uses: ./.github/workflows/sonar.yml
